// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardGroup: typeof import('./components/CardGroup.vue')['default']
    ConfettiCanvas: typeof import('./components/ConfettiCanvas.vue')['default']
    CustomCard: typeof import('./components/CustomCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NaiveProvider: typeof import('./components/NaiveProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./components/Side.vue')['default']
  }
}
